name: dsci-532-dashboard
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - altair
  - vega_datasets
  - plotly
  - dash
  - flask
  - jupyterlab
  - notebook
  - ipykernel
  - black
  - ruff
